updated references from spacefx-core

diff --git a/.github/workflows/run-integrationTests-dotnet.yaml b/.github/workflows/run-integrationTests-dotnet.yaml
--- a/.github/workflows/run-integrationTests-dotnet.yaml
+++ b/.github/workflows/run-integrationTests-dotnet.yaml
@@ -21,7 +21,7 @@ on:
 
 jobs:
   build-and-test:
-    name: build-and-test-core-${{ inputs.WORKFLOW_AGENT }}
+    name: test-spacefx-client-dotnet-${{ inputs.WORKFLOW_AGENT }}
     runs-on: ${{ inputs.WORKFLOW_AGENT }}
     permissions:
       contents: read
@@ -67,9 +67,9 @@ jobs:
     - name: Build Projects
       shell: bash
       run: |
-        [[ ! -f /var/spacedev/tmp/spacesdk-core/container_info.json ]] && echo "container_info.json not found.  Dev container start up failed" && exit 1
+        [[ ! -f /var/spacedev/tmp/${{ inputs.app_name }}/container_info.json ]] && echo "container_info.json not found.  Dev container start up failed" && exit 1
         echo "Calculating container name from container_info.json..."
-        DEV_CONTAINER_NAME=$(jq -r </var/spacedev/tmp/spacesdk-core/container_info.json '.[0].Name')
+        DEV_CONTAINER_NAME=$(jq -r </var/spacedev/tmp/${{ inputs.app_name }}/container_info.json '.[0].Name')
 
         # Remove the first character if it is a slash
         [[ ${DEV_CONTAINER_NAME:0:1} == "/" ]] && DEV_CONTAINER_NAME="${DEV_CONTAINER_NAME:1}"
@@ -89,9 +89,9 @@ jobs:
       shell: bash
       run: |
 
-        [[ ! -f /var/spacedev/tmp/spacesdk-core/container_info.json ]] && echo "container_info.json not found.  Dev container start up failed" && exit 1
+        [[ ! -f /var/spacedev/tmp/${{ inputs.app_name }}/container_info.json ]] && echo "container_info.json not found.  Dev container start up failed" && exit 1
         echo "Calculating container name from container_info.json..."
-        DEV_CONTAINER_NAME=$(jq -r </var/spacedev/tmp/spacesdk-core/container_info.json '.[0].Name')
+        DEV_CONTAINER_NAME=$(jq -r </var/spacedev/tmp/${{ inputs.app_name }}/container_info.json '.[0].Name')
 
         # Remove the first character if it is a slash
         [[ ${DEV_CONTAINER_NAME:0:1} == "/" ]] && DEV_CONTAINER_NAME="${DEV_CONTAINER_NAME:1}"
